-- phpMyAdmin SQL Dump
-- version 2.6.4-pl3
-- http://www.phpmyadmin.net
-- 
-- Host: db435736022.db.1and1.com
-- Generation Time: Mar 22, 2014 at 02:52 PM
-- Server version: 5.1.73
-- PHP Version: 5.3.3-7+squeeze19
-- 
-- Database: `db435736022`
-- 

-- --------------------------------------------------------

-- 
-- Table structure for table `Casas`
-- 

CREATE TABLE `Casas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `localidad` varchar(255) COLLATE latin1_spanish_ci NOT NULL,
  `precio` int(11) NOT NULL,
  `hab` int(11) NOT NULL,
  `desc_eng` longtext COLLATE latin1_spanish_ci NOT NULL,
  `cat` varchar(255) COLLATE latin1_spanish_ci NOT NULL,
  `provincia` varchar(255) COLLATE latin1_spanish_ci NOT NULL,
  `wc` int(11) NOT NULL,
  `zona` longtext COLLATE latin1_spanish_ci NOT NULL,
  `ref` varchar(255) COLLATE latin1_spanish_ci NOT NULL,
  `titulo` longtext COLLATE latin1_spanish_ci NOT NULL,
  `caract` longtext COLLATE latin1_spanish_ci NOT NULL,
  `parking` varchar(255) COLLATE latin1_spanish_ci NOT NULL,
  `sold` int(11) NOT NULL,
  `reserved` int(11) NOT NULL,
  `comunidad` varchar(255) COLLATE latin1_spanish_ci NOT NULL DEFAULT '-',
  `ibi` varchar(255) COLLATE latin1_spanish_ci NOT NULL DEFAULT '-',
  `m_const` varchar(255) COLLATE latin1_spanish_ci NOT NULL DEFAULT '-',
  `m_parcela` varchar(255) COLLATE latin1_spanish_ci NOT NULL DEFAULT '-',
  `year` varchar(255) COLLATE latin1_spanish_ci NOT NULL DEFAULT '-',
  `reformado` varchar(255) COLLATE latin1_spanish_ci NOT NULL DEFAULT '-',
  `heating` varchar(255) COLLATE latin1_spanish_ci NOT NULL DEFAULT '-',
  `pool` varchar(255) COLLATE latin1_spanish_ci NOT NULL DEFAULT '-',
  `map_search` varchar(255) COLLATE latin1_spanish_ci NOT NULL,
  `sea_views` varchar(255) COLLATE latin1_spanish_ci NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE KEY `ref` (`ref`),
  FULLTEXT KEY `titulo` (`titulo`),
  FULLTEXT KEY `caract` (`caract`)
) ENGINE=MyISAM AUTO_INCREMENT=178 DEFAULT CHARSET=latin1 COLLATE=latin1_spanish_ci AUTO_INCREMENT=178 ;

-- 
-- Dumping data for table `Casas`
-- 

INSERT INTO `Casas` VALUES (98, 'Orihuela Costa', 83000, 3, 'Spacious duplex townhouse with patio and terrace, very near the sea, in la Zenia, 100m2 house + terrace, spacious living room of 40 m2, furnished, fully equipped kitchen, 3 bedrooms, 2 bathrooms and communal pool.', 'Duplex', 'ALICANTE', 2, 'La Zenia', 'O310', '3 bedrooms, 2 bath Duplex in La Zenia', 'front terrace,back patio,community pool,fireplace,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (97, 'Torrevieja', 115000, 3, 'Beautiful semidetached duplex in Los Altos with 3 bedrooms and 2 bathrooms, it also has a separate kitchen, is fully furnished to the highest standards. It has a big solarium, a communal pool and it is located in a quiet area, has panoramic views of all the area, from the famous salinas, to the beach.', 'Duplex', 'Alicante', 2, 'Los Altos', 'T121', 'Semidetached Duplex in Los Altos', 'Big solarium,Communal pool,Great views,Separate kitchen,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (96, 'Orihuela Costa', 128000, 3, 'Beautiful semidetached Duplex with 230m2 plot and 110 m2 living space with a lovely garden and communal swimmingpool, solarium, Located in a very quite area, Next to commercial center, Close to Torrevieja and golf courses, Walk distance to restaurants, chemist and all amenities, 1 km to the beach. ', 'Duplex', 'ALICANTE', 2, 'Orihuela costa Serena IV', 'O309', 'Semidetached Duplex in Serena IV', 'next to commercial center,1 km to the beach,community pool,beautiful garden,solarium,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (95, 'Torrevieja', 88000, 2, 'Very nice 2 bed apartment with magnificent sea views in an exclusive area next to Punta Prima beach communal pool with a large and beautiful garden with playground.', 'Apartment', 'ALICANTE', 1, 'ROCIO DEL MAR', 'T120', '2 Bed Apartment with sea views', 'sea views,glazed balcony,comunal swimmpool,beautiful garden,,,,,,,,,,,,,,,', '1', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (94, 'Torrevieja', 52000, 2, 'nice 2 bedroom penthouse with 1 bathroom, separate kitchen and a nice balcony, there is a communal pool and its only 3 streets away from the beach.', 'Penthouse', 'Alicante', 1, 'Playa del Cura', 'T119', '2 bedroom Penthouse near Playa del Cura', '3 streets away from the beach,Communal pool,,,,,,,,,,,,,,,,,', '0', 1, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (93, 'Torrevieja', 130000, 2, 'Lovely 2 bedroom wooden villa in Montesinos on a 4500m plot, It has a nice swimmingpool and it is located in a quiet area, It also has an romm upstairs and a barbecue in an amazing porch.', 'Villa', 'Alicante', 1, 'Montesinos', 'T118', 'Amazing villa 4500 m in Montesinos', 'Swimmingpool,Barbecue,4500m plot,lovely views,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (92, 'Torrevieja', 215000, 2, 'Beautiful 2 bedroom penthouse in Cabo Mar. It is fully equiped, has air conditioning, glazed terrace, 60 m solarium, separate kitchen. Furnished with the highest quality. There are 3 community pools.', 'Penthouse', 'Alicante', 1, 'Cabo Mar', 'T117', 'Luxury penthouse in Cabo Mar', 'Community pool,Air conditioning,Glazed terrace,,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (91, 'Torrevieja', 155000, 2, 'Beautiful 2 bedroom penthouse in Cabo Mar. It is fully equiped, has air conditioning, glaced terrace, 60 m solarium, separate kitchen. There are 3 community pools', 'Penthouse', 'Alicante', 1, 'La Mata', 'T116', 'Penthouse in Cabo Mar', 'Solarium,Community pool,Air conditioner,Glaced terrace,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (90, 'San Javier', 76000, 2, 'Lovely ground floor apartment 1 minute away from mar menor beach at Lo Pagan, Close to supermarket, chemist, bus stop and all amenities, Ideal for living the whole year or spend your holidays.', 'Apartment', 'Murcia', 1, 'Lo Pagan', 'M705', 'Apartment in Mar Menor beach', '50 m to the beach,furnished,patio,perfect conditions,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (88, 'Orihuela Costa', 83000, 2, 'Apartment in Punta Prima very close to the beach, beautiful views, community pool, south facing, 2 bedrooms, 1 bathroom.', 'Apartment', 'Alicante', 1, 'Punta Prima', 'O308', '2 bed Apartment in Punta Prima', 'South facing,Nice views,Community pool,,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (87, 'Torrevieja', 95000, 3, 'Magnificent 3 bedroom Apartment with sea views,nicely orientated, parking area, community pool, next to supermarket and all amenities. Very close to the lovely Punta Prima beach. 5 minutes to Torrevieja.', 'Apartment', 'Alicante', 1, 'Rocio del Mar', 'T114', '3 bedroom Apartment in Rocio del Mar', 'Community pool,Parking area,Lovely sea views,South-East facing,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (85, 'Torrevieja', 56000, 1, 'Apartamento reformado a escasos 50m de la playa. Plaza de garaje incluida. Se encuentra en un estado impecable.', 'Apartment', 'Alicante', 1, 'Curva del palangre', 'T112', 'Apartamento 1 dorm a 50m de la playa', 'Reformado,Muy cercano a la playa,Garaje,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (86, 'Torrevieja', 60000, 2, 'Estupendo atico de 2 habitaciones muy cercano a la Playa de los Locos. Estupendo estado, céntrico y cercano a todos los servicios.', 'Penthouse', 'Alicante', 1, 'Playa de los locos', 'T113', 'Atico Playa de los Locos', 'Zona de playa,A 50m de la playa,,,,,,,,,,,,,,,,,', '0', 1, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (84, 'Torrevieja', 75000, 2, '', 'Apartment', 'Alicante', 1, 'Avda. Habaneras', 'T111', 'Apartamento Avda. Habaneras', 'Bonitas vistas,A 50m de la playa,,,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (82, 'Orihuela Costa', 775000, 3, 'Magnificent villa en Dehesa de Campoamor on a 10000m2 plot with 3 bed, 3 bath, privet winter swimmingpool, Closed garage and extra guests house, Communal sports area with 2 swimmingpool, tennis and padel court, 600m to the beach', 'Villa', 'ALICANTE', 3, 'Dehesa de Campoamor', 'O306', 'VILLA DEHESA DE CAMPOAMOR', 'winter swimmingpool,garage,solar energy,beautigul garden,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (83, 'Orihuela Costa', 190000, 2, 'Lovely, modern and fully furnished first floor apartment with south facing balcony and sea views, it consists of two large bedrooms, two bathrooms, semi-open kitchen with breakfast bar, marble floors, built in wardrobes, airconditioning h/c, underfloor heating in the bathrooms, underground parking and storage, secure complex with 24h security and CCTV cameras and  two beautifil communal pools.', 'Apartment', 'Alicante', 2, 'Punta Prima', 'O307', 'BEAUTIFUL APARTMENT IN PUNTA PRIMA', '16m2 terrace,85m2 living area,south facing,2 swimmingpools,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (81, 'Torrevieja', 76000, 3, 'Semidetached Duplex, 3 bedrooms, 2 bathrooms, storage room, solarium, garden. 70m2 built, 150m2 garden. 1 minute walk to the best swimmingpool in the area.', 'Duplex', 'ALICANTE', 2, 'Urb Lago Sal', 'T110', 'SEMIDETACHED DUPLEX <br> URB. LAGO SAL', 'privat garden,south esast facing,solarium,very quiet area,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (79, 'Pilar de la Horadada', 65000, 3, '3 bed, 1 bad flat in the center of Torre de la Horadada, balcony with sea views, separate kitchen with patio, 3rd floor without lift.', 'Apartment', 'ALICANTE', 1, 'Torre de la Horadada', 'P508', '3 Bed Flat in Torre de la Horadada', '2 minutes to the beach,separated kitchen,balcony with sea views,,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (80, 'Torrevieja', 78000, 2, 'Terrace house in a very quiet location with several gardens in one of the best area of Torrevieja, walking distance to the beach and downtown.', 'Apartment', 'Alicante', 1, 'Urb Los Angeles', 'T109', 'Terrace house in Urb Los Angeles', 'Front garden,Rear patio,Very quiet area,walking distance to the beach,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (78, 'Dehesa de Campoamor', 145000, 3, '3rd floor flat in the centre of Campoamor, with 3 bedrooms, 2 bathrooms, living - dining room, independent kitchen with utility room, glazed large terrace with views. Parking. Close to the beach and to all the ammenities.', 'Apartment', 'ALICANTE', 2, 'Dehesa de Campoamor', 'O305', '3 bed Flat in Dehesa de Campoamor', 'GLACED TERRACE,CLOSE TO THE BEACH,SPORT AREA,,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (77, 'Mil Palmeras', 46000, 0, 'Renovated, fully furnished and equipped, ground-floor studio apartment, South facing, glazed balcony, Located in a very quite area with gardens and very close to the fabulous Mil Palmeras beach, Store-room in basement, garden and private, off-road parking area, Bars, restuarants, supermarket, pool, etc., all close-by. ', 'Apartment', 'ALICANTE', 1, 'MIL PALMERAS', 'P507', 'Ground floor Studio in Mil Palmeras', 'South facing,Glazed balcony,close to the beach,quite area,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (76, 'Torrevieja', 54000, 2, '2 bedroom, 1 badroom penthouse apartment with lovely views, norh facing, 2 big community swimmingpools, very close to downtown, medical center, chemist, schools and commercial center.', 'Penthouse', 'Alicante', 1, 'Next Torreaguas', 'T108', 'Penthouse with swimmingpool, Torrevieja', '5 minutes from the beach,5 minutes from Habaneras,3 minutes to center,2 big community pools,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (74, 'Torrevieja', 79000, 3, 'Semidetached 3 bed, 2 bath, south-east facing, front garden, solarium, 177 m2 plot, very close to the best swimmingpool in the area, in a very quiet location.', 'Town house', 'ALICANTE', 2, 'PUNTA VIBORA', 'T107', 'SEMIDETACHED IN URB LAGO SAL', 'Front garden,Solarium,,,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (75, 'Orihuela Costa', 98000, 3, 'Terraced house, 2 bedrooms and 1 badroom downstairs an an extra independent bedroom with bathroom upstairs with acces from the garden, solarium, Next to restaurants and shops and 5 minutes to the several choice of golf courses in the area.', 'Town house', 'ALICANTE', 2, 'LOS DOLSES', 'O304', '3 bed, 2 bath Terraced house in Los Dolses', 'front and back garden,solarium,next to golf courses,near amenities,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (71, 'Dehesa de Campoamor', 55000, 1, 'Studio in the center of Campoamor, 35m2 with 1 bedroom, living room, bathroom and kitchen with windows, East facing, Incredible views, 300m to the beach, parking space, Next to supermarket restaurants and sports area.', 'Apartment', 'Alicante', 1, 'Dehesa de Campoamor', 'O303', '1 Bedroom Apartment in Dehesa de Campoamor', '300 m beach,east facing,sport area,parking,,,,,,,,,,,,,,,', '1', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (72, 'Pilar de la Horadada', 135000, 2, 'Reformed bungalow looking at a park with south facing front garden, 250 m to the fabulous Mil Palmeras beach, close to swimmingpool, restaurants,supermarket, etc, very close to magnificent choice of golf courses, 2 minutes to motorway access gives easy communication to Alicante and Murcia airports.', 'Bungalow', 'Alicante', 1, 'Mil Palmeras', 'P509', '2 Bed Bungalow in Mil Palmeras', 'front garden,south facing,overlooking a park,250m to the beach,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (70, 'Dehesa de Campoamor', 130000, 1, 'Studio in the center of Campoamor, 35m2 with 1 bedroom, bathroom, kitchen and living room, nicely refurbished, glaced balcony with incredible views, 300m to the beach, parking space. ', 'Apartment', 'Alicante', 1, 'Dehesa de Campoamor', 'O302', '1 Bedroom Apartment in Dehesa de Campoamor ', 'Glaced balcony,Nice refurbished,300m to the beach,,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (69, 'San Javier', 165000, 3, 'Lovely villa in a residential area with a big glazed terrace and private swimmingpool, extra guests separated bedroom, big plot of land next to the villa, 10 km to Mar Menor beach. ', 'Finca', 'Murcia', 1, 'Balsicas', 'M704', 'FINCA WITH SWPOOL IN RESIDENTIAL AREA BALSICAS', 'Conservatory,Swimminpool,10km to the beach,2ooom2 plot,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (68, 'Torrevieja', 140000, 2, 'Exclusive 2 bedrooms apartment very first line of the lovely and highly valued Cabo Cervera area, facing La Mata beach, 60m2 with 16m2 terrace, north east facing makes it ideal for summer holydays.', 'Apartment', 'ALICANTE', 1, 'Urb. Cabo Cervera', 'T106', 'FIRST LINE APARTMENT CABO CERVERA', '60 m2 apartment,16 m2 balcony,wonderful views,La Mata beach,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (67, 'Torrepacheco', 190000, 3, 'Finca 1650m2 plot and 105m2 built, near El Jimenado, Torre Pacheco, big swimmingpool area with bar, garden and several departments for animals, 146m2 patio with barbacue.', 'Finca', 'MURCIA', 2, 'EL JIMENADO', 'M703', 'FINCA WITH BIG SWIMMINGPOOL AREA EL JIMENADO MURCIA', 'SWIMMINGPOOL WITH BAR,PATIO WITH BARBACUE,SOUTH FACING,AREA FOR ANIMALS,1650m2 plot,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (66, 'Mil Palmeras', 98000, 2, 'Upper floor 2 bedroom bungalow, with two open terraces on both the ground floor and the upper floor, very close to the fabulous Mil Palmeras beach and a magnificent swimmingpool area, next to supermarket, chemist and restaurants, direct motorway accest gives easy communications with a magnificent choice of golfcourses as well as Alicante and Murcia airport.', 'Bungalow', 'ALICANTE', 1, 'MIL PALMERAS', 'P505', 'Bungalow in Mil Palmeras', 'close to the beach,walking distance to all amenities,very quiet area,close to golfcourses,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (65, 'Torrevieja', 89000, 3, 'Terraced house in a very quiet area of Torrevieja surrounded by several gardens 5 minutes to downtown and walking distance to the beach, medical center, supermarket and restaurants.', 'Town house', 'Alicante', 1, 'Urb Los Angeles', 'T105', 'TERRACED HOUSE IN URB LOS ANGELES', 'Conservatory,Front garden,South facing,Rear patio,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (64, 'Pilar de la Horadada', 270000, 5, 'Magnificet villa with big garden and lovely views in a very quiet urbanization, very close to Lo Romero golf course and 5 minutes drive to the lovely Torre de la Horadada beaches.', 'Villa', 'Alicante', 2, 'Pinar de Campoverde', 'P504', 'MAGNIFICENT VILLA IN PINAR DE CAMPOVERDE', '1100m2 plot,magnificet views,corner plot,big garden,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (61, 'Pilar de la Horadada', 78000, 3, 'Renovated Townhouse with large cellar in the center of Pinar de Campoverde, Lovely views, Walking distance of supermarket, chemist, restaurants and doctor, the golf course is 5 minutes away.', 'Town house', 'Alicante', 2, 'Pinar de Campoverde', 'P503', 'Townhouse in Pinar de Campoverde', 'glazed terrace,cellar,garden,patio,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (62, 'San Javier', 95000, 2, 'Renovated country house, 181m2 house on a 1220m2 plot, very close to Dos Mares commercial center. and 5 minutes to Mar Menor beach.', 'Finca', 'Murcia', 1, 'San Javier', 'M702', 'FINCA 1220M2 IN SAN JAVIER, MURCIA', 'land in front of house 700m2,front garden,rear patio 250m2,,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (63, 'Torrevieja', 59900, 2, 'ACEQUION BEACH SIDE SEA VIEW APARTMENT, FULLY FURNISHED. PERFECT CONDITIONS.', 'Apartment', 'Alicante', 1, 'Acequion', 'T122', 'SEA VIEW APARTMENT PLAYA ACEQUION', 'SEA VIEWS,GLAZED BALCONY,PERFECT CONDITIONS,FULLY FURNISHED,,,,,,,,,,,,,,,', '0', 1, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (59, 'Torrevieja', 86000, 3, 'Semidetached Duplex, 3 bedrooms, 2 bathrooms, 2 kitchens, conservatory, solarium, garage, garden, 70m2 built, 150m2 garden, In front of the best swimmingpool in the area.', 'Duplex', 'Alicante', 2, 'Res. Lago Sal', 'T103', 'SEMIDETACHED DUPLEX URB LAGO SAL', '2 kitchens,glazed terrace,garden,private garage,solarium,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (60, 'Torrevieja', 205000, 3, 'First line apartment in a lovely area next to the beach and 5 minutes from Torrevieja and Orihuela Costa, Enclosed community with swimmingpool, tennis court and parkig, Communal green area along the see with playground.', 'Apartment', 'Alicante', 2, 'MAR AZUL', 'T104', 'FRONT LINE APARTMENT IN URB. MAR AZUL', 'privet parking,tennis court,communal pool,gated community,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (99, 'Torrevieja', 48000, 2, 'Lovely first floor apartment with 2 bedrooms and 1 bathroom, glazed terrace, south facing, completely furnished, communal swimmingpool, walking distance to Habeneras commertial center, downtown, close to schools, supermarket and chemist, near the beach.', 'Apartment', 'Alicante', 1, 'La Tejera', 'T123', '2 bedroom Apartment in Torrevieja', 'Community pool,South facing,Glazed terrace,5 minutes to the beach,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (100, 'Torrevieja', 189000, 2, 'Great opportunity of a villa in urb Los Balcones, 740m2 plot, built in 1975, propane heating system, Torrevieja, 2 bed, 1 bath, solarium and closed garage, front and back garden, close to commercial center, restaurnats and Torrevieja Hospital, 2 km to the beach and 5 mts drive to Torrevieja center.', 'Villa', 'Torrevieja', 1, 'Los Balcones, Torrevieja', 'T124', 'Villa in Los Balcones', '800m2 plot,glazed terrace,south east  facing,closed garage,front and back garden,solarium,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (101, 'Orihuela Costa', 185000, 3, 'Lovely villa in Playa Flamenca, 540m2 plot, 3 bed, 2 bath, privet swimmingpool, 5 minutes to the beach, very close to the several choice of golf courses in the areea, next to all amenities and Zenia Boulevard comertial center, 10 minutes drive to Torrevieja.', 'Villa', 'Alicante', 2, 'Playa Flamenca', 'O311', 'Villa in Playa Flamenca', '540m2 plot,private swimmingpool,close to golf courses,5 minutes to the beach,,,,,,,,,,,,,,,', '0', 1, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (102, 'Pilar de la Horadada', 127000, 2, 'Lovely bungalow in Torre de la Horadada, built with the highest quality materials, it has a separate kitchen, 2 bedrooms, 2 bathrooms, just 2 minutes walking distance to the beach, very nice community pool, quiet area, ground floor or upper floor.', 'Bungalow', 'Alicante', 2, 'Torre de la Horadada', 'P510', 'Bungalow in Torre de la Horadada', 'Community pool,2 minutes to the beach,New construction,Front terrace or solarium,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (103, 'Pilar de la Horadada', 160000, 3, 'Lovely bungalow in Torre de la Horadada, built with the highest quality  materials, it has a separate kitchen, 2 bedrooms, 2 bathrooms, just 2 minutes walking distance to the beach, very nice community pool, quiet area, ground floor or upper floor.', 'Bungalow', 'Alicante', 2, 'Torre de la Horadada', 'P511', 'Bungalow in Torre de la Horadada', 'Community pool,2 minutes to the beach,New construction,Front terrace,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (104, 'Orihuela Costa', 203250, 2, 'Exclusive beachfront apartments of 2, 3 and 4 bedroom in a high-level residential complex with communal pools and closed garage in an exclusive area of Dehesa de Campoamor.', 'Bungalow', 'Alicante', 2, 'Dehesa de Campoamor', 'O312', 'First line in Dehesa de Campoamor', 'first line of the beach,exclusive area,communal swimmingpool ,closed garage,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (105, 'Torrevieja', 125000, 2, 'Great oportunity fantastic renovated duplex with lovely sea views,2 bed, 2 bath, front terrace, south facing, separated kitchen, closed to amenities and 2 minutes to downtown.', 'Duplex', 'Alicante', 2, 'Cala Zorra', 'T125', 'Duplex 2 dorm primera linea', 'sea views,front terrace,south facing,close to amenities,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (106, 'Torrevieja', 65000, 1, 'Very nice 1 bedroom apartment with sea views in a quiet area in Cabo Cervera, separate kitchen, fully furnished, with a nice terrace and a storage room, located in a great community with a lovely pool, just 1 minute away from the amazing La Mata beach.', 'Apartment', 'Alicante', 1, 'Cabo Cervera', 'T126', 'Upper floor apartment 1 minute to the beach', 'Community pool,Sea views,Quiet area,Terrace,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (107, 'Torrevieja', 65000, 1, 'Very nice 1 bedroom apartment in a quiet area in Cabo Cervera, separate kitchen, fully furnished, with a big terrace, located in a great community with a lovely pool, just 1 minute away from the amazing La Mata beach.', 'Apartment', 'Alicante', 1, 'Cabo Cervera', 'T127', 'Ground floor apartment 1 minute to the beach', 'Community pool,Terrace,Quiet area,1 minute to the beach,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (108, 'Torrevieja', 105000, 2, 'Amazing Duplex in a lovely area in Cabo Cervera, very nice views over the beautiful community pool, it has an american style kitchen, fully furnished and is in perfect condition, it is very close to the beach, located in a quiet and select area.', 'Duplex', 'Alicante', 2, 'Cabo Cervera', 'T128', 'Duplex 100 meters to the beach', 'Community pool,Terrace,Views of the pool,Quiet area,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (109, 'Torrevieja', 235000, 3, 'Lovely Villa in Los Balcones, 3 bedrooms, 2 bathrooms, 800m2 plot, 100m2 built size, built in 1988, private swimmingpool, glazed terrace, closed garage, storage room, next to supermarket, chemist, restaurants and all amenities.', 'Villa', 'Alicante', 2, 'Los Balcones', 'T129', 'Lovely villa in Los Balcones', 'private swimmingpool,800 m2 plot,next to all amenities,glazed terrace,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (110, 'Orihuela Costa', 97000, 2, 'Great apartment, 2 bedrooms, 2 bathrooms, separated kitchen, nice terrace overlooking the communal swimmingpool and garden, private parking, very close to golf courses and all amenities, 1 km to the beach.', 'Apartment', 'Alicante', 2, 'Villamartin', 'O313', 'Great apartment next to Villamartin', 'separated kitchen,marbel floors,communal swmmingpool,private parking,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (111, 'Torrevieja', 46000, 2, 'Bargain terrace house in Torreta III, 2 bedrooms, 1 bathroom, nice kitchen, big fron terrace, close to the best swimmingpool in the area, and walking distance to supermarket, restaurants and bus stop, 3 km to the beach and Torrevieja.', 'Town house', 'Alicante', 1, 'Torreta III', 'T130', '2 bedrooms Townhouse', 'big front terrace,quiet area,3 km to the beach,close to swimmingpool,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (112, 'Orihuela Costa', 72000, 2, 'Very nice refurbished 2 bedrooms, 2 bathrooms townhouse in urb Pueblo Principe, Orihuela Costa, 2 minutes to Villamartin, Las Ramblas and Campoamor golf course, next to supermarket, chemist and restaurants and 5 minutes drive to the wonderfull Campoamor beach.', 'Town house', 'Alicante', 2, 'Pueblo Principe', 'O314', '2 Bedrooms Townhouse in Orihuela Costa', 'front terrace,back patio,solarium,close to golfcourses,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (113, 'Torrevieja', 120000, 3, 'Lovely 3 bed, 2 bath duplex with front garden and solarium in a very nice and gated development, very close to La Mata beach, community pool, private parking and gardens walking distance to supermarket and all amenities.', 'Duplex', 'Alicante', 2, 'La Mata', 'T131', '3 bedrooms duplex in La Mata', 'gated community,solarium,community pool,private parking,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (116, 'Orihuela Costa', 135000, 2, 'This spacious 2 bedroom, 2 bathroom corner duplex is situated in a very quiet area, close to Villamartin, The property consists of a large lounge/diner with a separate fitted kitchen with access to the garden. Upstairs there are two bedrooms, a bathroom and a sun terrace, this property has a big garden and communal pool.\r\n', 'Duplex', 'Alicante', 2, 'Villamartin', 'O315', 'Corner duplex near Villamartin', 'Very quiet area,Southeast facing,Communal pool,Large garden,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (117, 'Orihuela Costa', 138000, 2, 'Wonderful 2 bed, 2 bath, ground floor apartment in Los Dolses, with sea views, facing the lovely communal swimmingpool and gardens, south facing, close to all amenities.', 'Apartment', 'Alicante', 2, 'Los Dolses', 'O316', '2 bed apartments in Los Dolses', 'big front terrace,communal pool,sea views,close to amenities,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (118, 'Orihuela Costa', 77000, 3, '3 bed terrace house very close to golf courses, supermarket, school and all amenities, front garden, patio and solarium, communal swimmingpool.', 'Town house', 'Alicante', 1, 'Villacosta', 'O317', '3 bed terrace house in St James Hill', 'front garden,communal pool,solarium,close to golf courses,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (135, 'Orihuela Costa', 475000, 2, 'Villa 5 minutes walking distance to La Zenia beach, 600m2 plot, 2 baedrooms, 1 bathroom, sauna, private swimmingpool, garage, solarium, lovely and sunny garden.', 'Villa', 'Alicante', 1, 'La Zenia', 'O321', 'Villa next to La Zenia beach', 'private swimmingpool,sauna,solarium,600m2 plot,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (120, 'Orihuela Costa', 138000, 3, '', 'Duplex', 'Alicante', 2, 'Playa Flamenca', 'O318', 'Corner Duplex in Playa Falmenca', 'big garden,3 terraces,south east facing,privet garage,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (121, 'San Javier', 160000, 2, 'Lovely country house near Mar Menor beach, 2 bed, big bathroom, separated kitchen, gym, garage, big patio with barbecue and solarium, 200m2 plot next to the house, close to Dos Mares commercial center, San Pedro, San Javier and Murcia airport.', 'Finca', 'Murcia', 1, 'San Javier', 'M706', 'Country house in San Javier', '5 minutes from Mar Menor,close to amenitries,very quiet area,large patio and solarium,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (122, 'Torrevieja', 23500, 0, 'Nice Studio at La Mata, 25m2, sunny, refurbished, barbecue area, close to amenities, 350 meters to the lovely beach, wide salt lake views,  ideal for holidays or long term vacations.', 'Apartment', 'Alicante', 1, 'La Mata', 'T134', 'Nice Studio at La Mata', 'close to the beach,salt lake views,sunny orientated,refurbished,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (123, 'Orihuela Costa', 245000, 4, 'Lovely 4 bedroom, 3 bath duplex with 150m2 terraces and solarium in Dehesa de Campoamor, 500m to the magnificent La Glea beach and surrounded by green area, communal swimmingpool.', 'Duplex', 'Alicnate', 3, 'Dehesa de Campoamor', 'O319', 'Triplex in Dehesa de Campoamor', '110m2 built,150 m2 terraces,sea and country views,500 meters to the beach,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (125, 'Torrevieja', 45000, 1, '1 bedroom apartment 1st line, sea views at Cabo Cervera, east facing, first floor, very bright, equipped kitchen, glazed terrace, very close to La Mata beach, restaurants and services.', 'Apartment', 'Alicante', 1, 'Cabo Cervera', 'T135', '1st line 1 bed apartment La Mata', 'Quiet area,Close to amenities,Next to bus stop,,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (128, 'Torrevieja', 169000, 3, 'Great first line, 3 bedroom apartment right in Playa del Cura beach, Torrevieja, surrounded by shops, restaurants and all amenities, 100m2, glazed balcony with magnificent sea views, separated kitchen with laundry room, underground private parking.', 'Apartment', 'Alicante', 2, 'Playa del cura', 'T136', '1st line 3 bedroom Apartment', 'glazed balcony,separated kitchen,east and west facing,underground garage,,,,,,,,,,,,,,,', '1', 1, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (129, 'Torrevieja', 58000, 2, '2 bedroom apartment by the sea in Cabo Cervera, next to La Mata beach, south facing, second floor, built size 55m2, terrace, extra underground utility room, magnificent views in a very quiet area close to restaurants and services, community fee 373 per year.', 'Apartment', 'Alicante', 1, 'Cabo Cervera', 'T137', '2 bed apartment by the sea', 'sea views,south facing,sunny terrace,close to amenities,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (130, 'Torrevieja', 69900, 2, '2 bedroom apartment by the sea in Cabo Cervera, next to La Mata beach, south facing, fifth floor, 45m2, magnificent views in a very quiet area close to restaurants and services.', 'Apartment', 'Alicante', 1, 'Cabo Cervera', 'T138', '2 bed apartment by the sea', 'sea views,south facing,storage room,close to amenities,,,,,,,,,,,,,,,', '1', 1, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (131, 'Torrevieja', 47000, 1, '1 bedroom apartment very close to the lovely La Mata beach, 45 m2, south facing glaze balcony, close to amenities, ideal for holidays or to live all year.', 'Apartment', 'Alicante', 1, 'La Mata', 'T139', '1 bed apartment close to La Mata beach', '200 meters to the beach,glaze balcony,close to amenities,south facing,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (134, 'Torrevieja', 47000, 1, '1 bedroom apartment 1st line, sea views at Cabo Cervera, sout facing, first floor, very bright, equipped kitchen, glazed terrace, very close to La Mata beach, restaurants and services.', 'Apartment', 'Alicante', 1, 'Cabo Cervera', 'T141', '1 bedroom apartment in Cabo Cervera', 'quiet area,sea views,south facing,close to amenities,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (133, 'Torrevieja', 45000, 1, '1 bedroom apartment 1st line, sea views at Cabo Cervera, south facing, ground floor, very bright, equipped kitchen, glazed terrace, very close to La Mata beach, restaurants and services.', 'Apartment', 'Alicante', 1, 'Cabo Cervera', 'T140', '1 bedroom apartment in Cabo Cervera', 'quiet area,sea views,south facing,close to amenities,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (136, 'Torrevieja', 125000, 2, 'Lovely 2 bedroom apartment in Molino Blanco, La Mata, 50m2, glazed balcony, south facing, communal swimmingpool, walking distance to La Mata beach, close to supermarket, restaurants and all services.', 'Apartment', 'Alicante', 1, 'La Mata', 'T142', '2bed apartmanet in La Mata beach', 'communal swimmingpool,glazed balcony,near the beach,close to amenities,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (137, 'Torrevieja', 110000, 2, 'Nice 2 bedroom groundfloor apartment in Torrevieja, 60m2 plus front garden, 400 meters to the beautiful La Mata beach, separated kitchen and patio, south facing, communal swimmingpool, tennis court and children playgound, walking distance to supermarket, restaurants and all amenities.', 'Town house', 'Alicante', 1, 'La Mata', 'T143', '2 bedroom groundfloor apartment in La Mata', 'front garden,south facing,400 meters to the beach,communal swimmingpool,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (138, 'Torrevieja', 37000, 0, 'Nice studio with sea views, 39m2, walking distance to the beautiful La Mata beach, glazed balcony, separated kitchen, communal swimmingpool, closed to supermarket, restaurants and all services. ', 'Apartment', 'Alicante', 1, 'Torre del Moro', 'T144', 'sea views studio at La Mata', 'sea views,glazed balcony,community pool,close to amenities,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (139, 'Torrevieja', 69000, 1, '1 bedroom aparment in a private community with swimmingpool and gardens, 50m2, balcony, walking distance to the beautiful beach, close to all amenities.', 'Apartment', 'Alicante', 1, 'La Mata', 'T145', '1 bedroom apartment in La Mata', 'very quiet area,community pool,400 meters to the beach,close to amenities,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (140, 'Torrepacheco', 165000, 3, 'Beautiful Villa with private swimmingpool, 3 bedrooms, 2 bathrooms, solarium, extra guest house, 3900 m2 plot, 20 km to the beach and 18 km to Murcia, 1 km from the junction Mar Menor - Murcia motorway.', 'Finca', 'Murcia', 2, 'Valle del Sol', 'M707', 'Finca with swimpool and guest house', '3900m2 plot,private swimmingpool,guest house,20 km to the beach,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (146, 'Torrevieja', 43000, 1, '1 bedroom apartment with sea views, south facing, walking distance to the beach, glazed balcony, 3rd floor, without lift, communal swimmingpool, close to supermarket, restaurants and all amenities. ', 'Apartment', 'Alicante', 1, 'Torre del Moro', 'T147', '1 bedroom apartment La Mata', 'sea views,glazed balcony,communal pool,close to amenities,,,,,,,,,,,,,,,', '1', 0, 1, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (147, 'Torrevieja', 130000, 3, 'Nice 3 bedroom, 3 bathroom duplex with front garden and sea views in one of the best areas in Torrevieja, next to the sea,  ', 'Duplex', 'Alicante', 3, 'Rocio del Mar', 'T148', '3 bedroom Diplex in Mar azul', 'front terrace,sea views,barbacue,,,,,,,,,,,,,,,,', '1', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (148, 'Torrevieja', 71000, 2, '', 'Town house', 'Alicante', 1, 'La Mata', 'T149', 'End of Terrace Townhouse', 'sea views,,,,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (149, 'Torrevieja', 130000, 3, 'Nice 3 bedroom 3 bathroom Triplex in the lovely area of Mar Azul, sea views, front terrace with barbecue, very quiet area, close to Torrevieja y Orihuela Costa.', 'Duplex', 'Alicante', 2, 'Mar Azul', 'T150', '3 bedroom Triplex in urb Mar Azul', 'front terrace,sea views,quiet area,barbecue ,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (150, 'Torrevieja', 46000, 1, '1 bedroom apartment with sea views, south facing, walking distance to the beach, glazed balcony, 3rd floor, without lift, communal swimmingpool, close to supermarket, restaurants and all amenities. ', 'Apartment', 'Alicante', 1, 'Torre del Moro', 'T151', '', 'sea views,glazed balcony,communal pool,close to amenities,,,,,,,,,,,,,,,', '1', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (151, 'Orihuela Costa', 68000, 2, 'Stunning ground floor bungalow with 2 bedrooms, bathroom, spacious living room, kitchen, utility room, private garden entrance to the car, terrace, furnished and equipped, Spectacular urbanization within a pine forest with picnic area and swimming pool, video surveillance cameras, 1,6 km from the beach', 'Bungalow', 'Alicante', 1, 'Playa Flamenca', 'O322', '2 bedroom bungalow Playa Flamenca', 'gated community,front terrace,privet parking,close to amenities,,,,,,,,,,,,,,,', '1', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (152, 'Orihuela Costa', 69000, 2, 'Renovated ground floor apartment 350m to the beach, it has 2 bedrooms, bathroom, living room, kitchen, furnished, large double terrace, car parking.', 'Apartment', 'Alicante', 1, 'Punta Prima', 'O323', '2 bedroom Ground floor apartment Punta Prima', 'big terrace,ground floor,renovated,parking,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (153, 'Torrevieja', 49000, 2, 'Penthouse South facing, 35m2 terrace, 2 bedrooms, living room with fireplace, bathroom, independent kitchen, furnished, exterior, near the beach.', 'Penthouse', 'Alicante', 1, 'La Loma', 'T152', '2 Bedroom Penthouse with terrace', 'Terrace,Close to the beach,Fireplace,Fully furnished,,,,,,,,,,,,,,,', '0', 1, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (154, 'Orihuela Costa', 63000, 2, 'Ground floor bungalow with 2 bedrooms, kitchen, living room, bathroom, patio, private front garden, fully furnished, parking within the grounds and a lovely community pool.', 'Bungalow', 'Alicante', 1, 'Playa Flamenca', 'O324', 'Ground floor Bungalow in Las Mimosas', 'Front garden,Patio,Community pool,Private parking,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (155, 'Orihuela Costa', 53000, 2, 'Ground floor Bungalow with 2 bedrooms, bathroom, living room, kitchen, backyard, private garden, terrace, air conditioning, fully furnished, 200m away from public swimmingpool, facing east (morning sun), close to the beach.', 'Bungalow', 'Alicante', 1, 'La Florida', 'O325', 'Ground floor Bungalow in La Florida', 'Air conditioning,Garden,Fully furnished,Backyard,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (156, 'Orihuela Costa', 299000, 4, 'Lovely two floor villa in Los Balcones, very close to all the neccesary services, but located in a quiet and nice area. It has a swimmingpool, a garage with space for a large car, a large storage room, balcony, fully equipped kitchen, house is equipped with air conditioning and is sold unfurnished.', 'Villa', 'Alicante', 3, 'Los Balcones', 'O326', 'Beautiful 4 bedroom Villa in Los Balcones', 'Swimmingpool,Garage,Solarium,Air conditioning,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (157, 'Torrevieja', 59000, 2, 'Lovely 2 bedroom apartment in Mar Azul, fully furnished, american style kitchen, terrace with sea views, nice community pool, just 200 meters to the beach and near all amenities.', 'Apartment', 'Alicante', 1, 'Mar Azul', 'T153', '2 Bedroom Apartment in Mar Azul', 'Terrace,200m from the beach,Close to amenities,Communal pool,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (158, 'Orihuela Costa', 71000, 2, 'Stunning duplex in Villamartín, nice orientation, furnished with style, it has 2 big bedrooms, an american style kitchen, spacious livingroom and a nice front garden, it also has a community pool and is located in a quiet area.', 'Duplex', 'Alicante', 2, 'Villamartin', 'O327', '2 Bedroom Duplex in Villamartin', 'Private garden,Back patio,Community pool,Terrace,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (159, 'Orihuela Costa', 79000, 2, 'Very nice penthouse apartment in La Zenia, very sunny due to the good ideal orientation, near the beach, it has a completely refurbished kitchen, a livingroom with a fireplace, a terrace and a solarium with lovely sea views, there is also a parking area.', 'Penthouse', 'Alicante', 1, 'La Zenia', 'O328', '2 Bedroom Penthouse in La Zenia', 'Solarium,400m to the beach,Fireplace,Sunny orientation,,,,,,,,,,,,,,,', '1', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (160, 'Torrevieja', 43000, 2, 'Ground floor Bungalow in El Chaparral, completely renovated, with american style kitchen and patio, it has a 50 square meter garden, the bathroom has a window,  parking area, the property is sold unfurnished.', 'Bungalow', 'Alicante', 1, 'El Chaparral', 'T154', 'Ground Floor Bungalow in El Chaparral', 'Big garden,American  style kitchen,Patio,Parking area,,,,,,,,,,,,,,,', '1', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (161, 'Orihuela Costa', 84000, 2, 'Spectacular Quad with american style kitchen, large garden, glaced individual solarium, large living room with fireplace, fully furnished with air conditioning and a lovely communal pool.', 'Duplex', 'Alicante', 1, 'Playa Flamenca', 'O329', '2 Bedroom Quad in Serena 4', 'Patio,Communal pool,Glaced terrace,Air conditioning,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (162, 'Orihuela Costa', 79000, 3, 'Lovely 3 Bedroom Duplex in Playa Flamenca, it has a very nice terrace, american style kitchen, a large living room, private garden, patio, a communal pool and is fully furnished, it is also very near to Zenia Boulevard shopping center and the beach.', 'Duplex', 'Alicante', 3, 'Playa Flamenca', 'O330', '3 Bedroom Duplex in Playa Flamenca', 'Near shopping center,Private garden,Communal pool,Nice terrace,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (163, 'Orihuela Costa', 65000, 2, 'Completely refurbished Bungalow in Blue Lagoon with 2 bedrooms, a large dining room, american style kitchen, a nice garden, a large private solarium with magnificent views, a storage room, it is located in a quiet and nice area, without comunnity fees, and there is a public swimming pool nearby.', 'Bungalow', 'Alicante', 1, 'Blue Lagoon', 'O331', '2 Bedroom Bungalow in Blue Lagoon', 'Large Terrace,Storage room,Large solarium,Refurbished,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (164, 'Torrevieja', 70000, 2, 'Apartment in Rocio del Mar very close to the beach, beautiful views, community pool, north facing, 2 bedrooms, 1 bathroom, very close to amenities Torrevieja and Orihuela Costa.', 'Apartment', 'Alicante', 1, 'Rocio del Mar', 'T155', '2 bedroom apartment in Rocio del Mar', 'lovely views,community swimmingpool,close to amenities,exclusive area,,,,,,,,,,,,,,,', '1', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (165, 'Orihuela Costa', 68000, 0, 'Exclusive tipical Spanish Restaurante at Aguamarina, Campoamor, 154m2 with 12 dining tables inside (46 - 50 people), 60m2 terrace + 80 m2 extra terrace, near the beach, close to medical central, weekly market and 5 minutes drive to the 4 best golf courses in the area.', 'Commercial property', 'Alicante', 2, 'Campoamor', 'O332', 'Tipical Spanish Restaurant near the beach', 'leasing,two big terraces,open all year,near the beach,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (166, 'Orihuela Costa', 57000, 2, 'Nice ground floor 2 bedroom 56m2 bungalow with covered entrance porch and a 20m2 front garden, located in a gated residential community and it has the use of communal swimming pool, next to glof courses and very close to amenities.', 'Town house', 'Alicante', 1, 'Villa Costa', 'O333', '2 Bedroom Bungalow St James Hill', 'front terrace,communal swimming pool,gated community,next to golf courses,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (169, 'Torrevieja', 26000, 0, 'Beautiful studio with sea views in Torrevieja, 7th floor, excelent conditions, 27m2, walking distance to Los Locos and El Cura beaches, close to amenities, Community fee 114,4€ year, SUMA 83€ year.', 'Apartment', 'Alicante', 1, 'Avda. Habaneras', 'T157', 'Beautiful Studio in Torrevieja', 'sea views,renovated,7th  floor,close to amenities,,,,,,,,,,,,,,,', '1', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (170, 'Orihuela Costa', 59500, 2, 'Nice semidetached sunny bungalow in La Florida, 2 bedrooms, front glazed terrace, garage, solarium, quiet area, close to all local amenities.', 'Bungalow', 'Alicante', 1, 'La Florida', 'O335', 'Semidetached 2 bedroom Bungalow', 'front terrace,garage,solarium,west facing,,,,,,,,,,,,,,,', '1', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (171, 'Torrevieja', 79000, 3, 'Lovely 3 bedroom ground floor apartment in the center of Torrevieja, beautiful front garden with entrance for a car, glazed terrace, communal swimmingpool, walking distance to the beach,close to all amenities.', 'Apartment', 'Alicante', 1, 'La Loma', 'T158', 'Ground floor with lovely garden Torrevieja', 'Front garden,garage,communal swimmingpool,close to all amenities,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (172, 'Mil Palmeras', 62000, 1, 'Lovely first line 1 bedroom appartment in the beautiful Mil Palmeras beach, furnished, fully equipped kitchen, south facing balcony with sea views, close to all amenities, parking area.', 'Apartment', 'Alicante', 1, 'Mil Palmeras', 'P512', 'First line 1 bedroom Apartment', 'Sea views,South facing,Close to amenities,Parking area,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (173, 'Orihuela Costa', 39500, 1, 'Nice first floor bungalow, 1 bedroom, front terrace and garden, big basement, sold fully furnished, good conditions.', 'Bungalow', 'Alicante', 1, 'Blue Lagoon', 'O336', '1 bedroom Bungalow in Blue Lagoon', 'front terrace,garden,first floor,basement,,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
INSERT INTO `Casas` VALUES (174, 'Torrevieja', 53000, 2, 'Lovely ground floor apartment in Cabo Cervera, has 2 bedrooms, 1 bathroom, a nice living room with air conditioning, a large glazed terrace, just 50 meters to the magnificent Cabo Cervera beach and a lovely park, one of the best areas in Torrevieja.', 'Apartment', 'Alicante', 1, 'Cabo Cervera', 'T159', '2 bedroom Apartment in Cabo Cervera', 'Sea views,Quiet area,Glazed terrace,50 meters to the beach,,,,,,,,,,,,,,', '0', 0, 0, '', '0', '0', '0', '0', '', '', '', '', '0');
